-- 1. SOURCES TABLE
CREATE TABLE sources (
    "sourceID"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sourceName" VARCHAR(200) NOT NULL,
    "authors"    TEXT,
    "link"       TEXT NOT NULL,
    "start"      INT,
    "end"        INT,
    "created"    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "groupname"  VARCHAR(20) NOT NULL,
    "title"      VARCHAR(150) NOT NULL,
    "date"       DATE,
    CONSTRAINT link_unique UNIQUE ("link") -- Postgres text columns can have unique constraints
);

-- 2. CONTENTS TABLE
CREATE TABLE contents (
    "sourceID" INT PRIMARY KEY,
    "html"     TEXT,
    "text"     TEXT,
    "created"  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "embedding" vector(384)
);

-- Index for contents embedding
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relname = 'contents_embedding_ivfflat' AND n.nspname = current_schema()
    ) THEN
        EXECUTE 'CREATE INDEX contents_embedding_ivfflat ON contents USING ivfflat (embedding vector_cosine_ops)';
    END IF;
END$$;

-- 3. SENTENCES TABLE (The core search table)
CREATE TABLE sentences (
    "sentenceID"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sourceID"     INT NOT NULL,
    "hawaiianText" TEXT,
    "englishText"  VARCHAR(255),
    "created"      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "simplified"   TEXT,
    
    -- SEARCH CONFIGURATION
    -- We create a Generated Column that combines Hawaiian and Simplified text
    -- 'simple' dictionary is used to prevent aggressive English stemming on Hawaiian words
    "search_vector" tsvector GENERATED ALWAYS AS (
        to_tsvector('simple', coalesce("hawaiianText", '')) || 
        to_tsvector('simple', coalesce("simplified", ''))
    ) STORED
);

-- 4. SEARCH INDEXES AND FUNCTIONS
-- Base GIN full-text indexes (as currently present)
CREATE INDEX IF NOT EXISTS sentences_hawaiiantext_tsv_gin
    ON sentences USING GIN (to_tsvector('simple', coalesce(hawaiianText, '')));
CREATE INDEX IF NOT EXISTS sentences_simplified_tsv_gin
    ON sentences USING GIN (to_tsvector('simple', coalesce(simplified, '')));

-- Trigram GIN indexes to accelerate phrase searches (as currently present)
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS sentences_hawaiiantext_trgm_gin
    ON sentences USING GIN (hawaiianText gin_trgm_ops);
CREATE INDEX IF NOT EXISTS sentences_simplified_trgm_gin
    ON sentences USING GIN (simplified gin_trgm_ops);

-- Unaccent support for diacritic-insensitive search
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE OR REPLACE FUNCTION immutable_unaccent(text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT unaccent($1);
$$;

-- Functional indexes using unaccent (new)
CREATE INDEX IF NOT EXISTS sentences_unaccent_vec_gin
    ON sentences USING GIN (to_tsvector('simple', immutable_unaccent(hawaiianText)));
CREATE INDEX IF NOT EXISTS sentences_unaccent_trgm_gin
    ON sentences USING GIN (immutable_unaccent(hawaiianText) gin_trgm_ops);

-- Foreign key and common indexes
CREATE INDEX IF NOT EXISTS idx_sentences_source ON sentences (sourceid);

-- Ensure sentenceid is unique for FK references (older schemas may lack explicit PK/unique)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'sentences_sentenceid_unique'
    ) THEN
        ALTER TABLE sentences ADD CONSTRAINT sentences_sentenceid_unique UNIQUE (sentenceid);
    END IF;
END$$;

-- 5. Vectors support (pgvector) and embedding column on sentences
CREATE EXTENSION IF NOT EXISTS vector;
ALTER TABLE sentences
    ADD COLUMN IF NOT EXISTS embedding vector(384);
-- Recommended IVFFLAT index for cosine similarity (requires list initialization separately)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relname = 'sentences_embedding_ivfflat' AND n.nspname = current_schema()
    ) THEN
        EXECUTE 'CREATE INDEX sentences_embedding_ivfflat ON sentences USING ivfflat (embedding vector_cosine_ops)';
    END IF;
END$$;

-- 6. Documents table to store document-level text and vectors (metrics separate)
CREATE TABLE IF NOT EXISTS documents (
    doc_id BIGINT PRIMARY KEY,
    groupname VARCHAR(50),
    sourcename VARCHAR(255),
    authors TEXT,
    date DATE,
    link TEXT,
    title VARCHAR(255),
    text TEXT,
    text_vector vector(384)
);
CREATE INDEX IF NOT EXISTS documents_groupname_idx ON documents (groupname);
CREATE INDEX IF NOT EXISTS documents_text_vec_ivfflat ON documents USING ivfflat (text_vector vector_cosine_ops);

-- 7. Metrics tables (modular, extensible)
CREATE TABLE IF NOT EXISTS sentence_metrics (
    sentenceid INT PRIMARY KEY REFERENCES sentences(sentenceid) ON DELETE CASCADE,
    hawaiian_word_ratio REAL,
    word_count INT,
    length INT,
    entity_count INT,
    frequency INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS sentence_metrics_freq_idx ON sentence_metrics (frequency);

CREATE TABLE IF NOT EXISTS document_metrics (
    sourceid INT PRIMARY KEY REFERENCES contents(sourceid) ON DELETE CASCADE,
    hawaiian_word_ratio REAL,
    word_count INT,
    length INT,
    entity_count INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
